name: E-Lib CI

on: [push, pull_request]

jobs:
  e-lib-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mongodb
          coverage: none

      # Install MongoDB tools
      - name: Install MongoDB tools and verify connection
        run: |
          # Install MongoDB tools (correct package name)
          sudo apt-get update
          sudo apt-get install -y mongodb-database-tools
          
          # Verify MongoDB connection - No need for schema import
          mongosh --host localhost --port 27017 --eval "db.runCommand({ ping: 1 })" || echo "Using alternative MongoDB client"

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Start PHP server
        run: php -S 0.0.0.0:8000 -t public &
      
      - name: Set up ngrok
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok

      - name: Expose app via ngrok
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          ngrok http 8000 &
          sleep 5
          echo "App available at: $(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')"