name: E-Lib CI

on: [push, pull_request]

jobs:
  e-lib-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mongodb:2.0.0

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress
        # Fallback in case of extension installation issues
        continue-on-error: true
        id: normal-install

      - name: Install Composer dependencies (ignoring platform requirements)
        if: steps.normal-install.outcome == 'failure'
        run: composer install --prefer-dist --no-progress --ignore-platform-req=ext-mongodb

      - name: Import MongoDB schematics
        run: |
          mongoimport --host localhost --port 27017 --db LibraryDb --file MongoSchematics.png --type json

      - name: Start PHP server
        run: php -S 0.0.0.0:8000 -t public &
      
      - name: Set up ngrok
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok

      - name: Expose app via ngrok
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          ngrok http 8000 &
          sleep 5
          echo "App available at: $(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url')"