name: Test PHP Mongo App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6
        ports: [27017:27017]
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      run: |
        docker build -t my-php-app .

    - name: Run container for test
      run: |
        docker run -d --name my-php-app-test \
          --link $(docker ps -qf ancestor=mongo:6):mongo \
          -e MONGO_URI=mongodb://mongo:27017/myappdb \
          -p 8080:80 my-php-app

    - name: Wait for MongoDB
      run: sleep 10

    - name: Run health check
      run: |
        curl --fail http://localhost:8080 || exit 1
